### ISSUE TITLE
Spurious logging printout

### ISSUE THREAD

**Issue by UnnamedMoose** [UnnamedMoose/serialMonitor#23]
There seems to now be a lot of printout "Debug: Too many EndStyle calls" appearing after each line in the log. This is most likely coming from some wx issues, investigate and remove the root cause or at least suppress to keep the log file for relevant information only.

**Comment by AleksanderLidtke** [comment]
Sheds some light on #21 and possibly on #23

**Comment by AleksanderLidtke** [comment]
There are exactly five hits on Google when searching for `python "Too many EndStyle calls!" in log`. I guess suppression might be the way to go (´；Д；｀)

**Comment by AleksanderLidtke** [comment]
This warning does not appear to be thrown from within Python itself: grepping for `EndStyle` in the `wxpython` source directory doesn't find the above log message, only the following hits in non-source files (*.pyi files are only used by text editors to provide hints, they aren't sources _per se_):
```
./richtext.pyi:    def EndStyle(self):
./richtext.pyi:        EndStyle() -> bool
./richtext.pyi:    def EndStyle(self):
./richtext.pyi:        EndStyle() -> bool
./stc.pyi:    def GetEndStyled(self):
./stc.pyi:        GetEndStyled() -> int
./stc.pyi:    EndStyled = property(None, None)
```

Internet search hints that this issue is coming from the `wxRichTextBuffer` (source [link](https://github.com/wxWidgets/wxWidgets/blob/master/src/richtext/richtextbuffer.cpp)) and is thrown by this method:
```
/// End the style
bool wxRichTextBuffer::EndStyle()
{
    if (!m_attributeStack.GetFirst())
    {
        wxLogDebug(_("Too many EndStyle calls!"));
        return false;
    }

    wxList::compatibility_iterator node = m_attributeStack.GetLast();
    wxRichTextAttr* attr = (wxRichTextAttr*)node->GetData();
    m_attributeStack.Erase(node);

    SetDefaultStyle(*attr);

    delete attr;
    return true;
}
```
Solving this issue will require looking into the `wxRichTextBuffer` and understanding where in the Python bindings the its `EndStyle` methond called excessively...

**Comment by AleksanderLidtke** [comment]
Managed to fix the error by commenting out `self.logFileTextControl.EndTextColour()`, so that is the culprit of the spurious logging output. Need to understand how the issue can be resolved in a neater way. Maybe keep track of whether the colour needs to be reset? See commit [8b5fa1be45917ede43bee128c38402257117a9ce](https://github.com/AleksanderLidtke/serialMonitor/commit/8b5fa1be45917ede43bee128c38402257117a9ce) for more details.

**Comment by UnnamedMoose** [comment]
Fixed by calling the EndTextColour() if and only if BeginTextColour(colour) also gets called.
